CREATE DATABASE test;

USE test;


CREATE TABLE please (
EMP_NUM char(3) primary key,
EMP_LNAME varchar(15),
EMP_FNAME varchar(15),
EMP_INITIAL char(1),
EMP_HIREDATE date,
JOB_CODE char(3),
PROJ_NUM int
);

INSERT INTO please(EMP_NUM,EMP_LNAME,EMP_FNAME,EMP_INITIAL,EMP_HIREDATE,JOB_CODE,PROJ_NUM) VALUES ('101','News','John','G','2016-11-08','502',25);
INSERT INTO please(EMP_NUM,EMP_LNAME,EMP_FNAME,EMP_INITIAL,EMP_HIREDATE,JOB_CODE,PROJ_NUM) VALUES ('102','Senior','David','H','2017-07-12','501',0);
INSERT INTO please(EMP_NUM,EMP_LNAME,EMP_FNAME,EMP_INITIAL,EMP_HIREDATE,JOB_CODE,PROJ_NUM) VALUES ('103','Arbaugh','June','E','2016-12-01','500',18);
INSERT INTO please(EMP_NUM,EMP_LNAME,EMP_FNAME,EMP_INITIAL,EMP_HIREDATE,JOB_CODE,PROJ_NUM) VALUES ('104','Ramoras','Anne','K','2015-11-15','501',0);
INSERT INTO please(EMP_NUM,EMP_LNAME,EMP_FNAME,EMP_INITIAL,EMP_HIREDATE,JOB_CODE,PROJ_NUM) VALUES ('105','Johnson','Alice','K','2015-02-15','502',25);
INSERT INTO please(EMP_NUM,EMP_LNAME,EMP_FNAME,EMP_HIREDATE,JOB_CODE,PROJ_NUM) VALUES ('106','Smithfield','William','2017-06-22','500',18);
INSERT INTO please(EMP_NUM,EMP_LNAME,EMP_FNAME,EMP_INITIAL,EMP_HIREDATE,JOB_CODE,PROJ_NUM) VALUES ('107','Alonzo','Maria','D','2016-10-10','500',18);
 

UPDATE please SET JOB_CODE = '501' WHERE EMP_NUM = '107';

DELETE FROM please WHERE EMP_FNAME = 'William';


SELECT * FROM please

